name: moralar_tts
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  json_string: ^3.0.1
  moralar_widgets:
   path: '../Moralar-widgets'
#    git:
#      url: git@github.com:megaleios-git/moralar-widgets.git
  mega_flutter:
    path: '../mega-flutter'
#    git:
#      url: git@github.com:megaleios-git/mega-flutter
#      ref: v0.1.4
  brasil_fields: 1.1.4
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  get: 4.6.6
  mask_text_input_formatter: ^2.9.0
  validatorless: ^1.2.0
  path_provider:
  open_file:
  dio: ^4.0.6
  http:
  mime_type: ^1.0.0
  share: ^2.0.4
  hive: ^2.1.0
  flutter: 
    sdk: flutter
  video_player_web: ^2.3.3
  wakelock_web: ^0.4.0

dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

