name: moralar_tts
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  moralar_widgets:  
    path: '../moralar-widgets'
    # git:
    #   url: git@github.com:lucasbatista-megaleios/moralar-widgets.git
  mega_flutter:
    git:
      url: git@github.com:megaleios-git/mega-flutter
      ref: v0.1.1
      
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  get: 4.3.4
  mask_text_input_formatter: ^2.0.0
  validatorless: ^1.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

